module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testMatch: [
    '<rootDir>/tests/**/*.test.ts',
    '<rootDir>/continuum/packages/kernel/src/__tests__/**/*.test.ts',
    '<rootDir>/packages/*/src/__tests__/**/*.test.ts',
  ],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/legacy/',
    'max_compress_stack\\.e2e\\.test\\.ts$',
    'causal-memory\\.integration\\.test\\.ts$',
    'bounded-worker-script\\.integration\\.test\\.ts$',
    'api-pipeline-causal\\.integration\\.test\\.ts$',
    'omega_distributed_coordination\\.test\\.ts$',
    'omega_command_api\\.test\\.ts$',
    'omega_transition_boundary\\.test\\.ts$',
    'omega_reality_verification\\.test\\.ts$',
    'omega_pipeline\\.e2e\\.test\\.ts$',
    'omega_change_boundary\\.test\\.ts$',
    'worker-lifecycle\\.integration\\.test\\.ts$',
    'broken-current\\.integration\\.test\\.ts$',
    'full-loop\\.integration\\.test\\.ts$',
    'governance\\.test\\.ts$',
    'canonical-store-lifecycle\\.integration\\.test\\.ts$',
  ],
  moduleNameMapper: {
    '\\.\\./\\.\\./packages/([^/]+)/dist/index(\\.js)?$': '<rootDir>/packages/$1/src/index.ts',
    '\\.\\./\\.\\./apps/([^/]+)/dist/index(\\.js)?$': '<rootDir>/apps/$1/src/index.ts',
    '^(\\.{1,2}/.*)\\.js$': '$1',
    '^@oceanicos/types$': '<rootDir>/packages/types/src/index.ts',
    '^@oceanicos/observer$': '<rootDir>/packages/observer/src/index.ts',
    '^@oceanicos/verification$': '<rootDir>/packages/verification/src/index.ts',
    '^@oceanicos/remember$': '<rootDir>/packages/remember/src/index.ts',
    '^@oceanicos/mini$': '<rootDir>/packages/mini/src/index.ts',
    '^@oceanicos/generative$': '<rootDir>/packages/generative/src/index.ts',
    '^@oceanicos/mood$': '<rootDir>/packages/mood/src/index.ts',
    '^@oceanicos/attestation$': '<rootDir>/packages/attestation/src/index.ts',
    '^@oceanicos/inference$': '<rootDir>/packages/inference/src/index.ts',
    '^@oceanicos/vector$': '<rootDir>/packages/vector/src/index.ts',
    '^@oceanicos/authorization$': '<rootDir>/packages/authorization/src/index.ts',
    '^@oceanicos/pluralism$': '<rootDir>/packages/pluralism/src/index.ts',
    '^@omega-v/types$': '<rootDir>/packages/types/src/index.ts',
    '^@omega-v/observer$': '<rootDir>/packages/observer/src/index.ts',
    '^@omega-v/verification$': '<rootDir>/packages/verification/src/index.ts',
    '^@omega-v/attestation$': '<rootDir>/packages/attestation/src/index.ts',
    '^@omega-v/remember$': '<rootDir>/packages/remember/src/index.ts',
    '^@omega-v/mini$': '<rootDir>/packages/mini/src/index.ts',
    '^@omega-v/(.*)$': '<rootDir>/continuum/packages/$1/src/index.ts',
  },
  transform: {
    '^.+\\.tsx?$': [
      'ts-jest',
      {
        useESM: true,
        tsconfig: {
          target: 'ES2022',
          module: 'NodeNext',
          moduleResolution: 'NodeNext',
          esModuleInterop: true,
          skipLibCheck: true,
          isolatedModules: true,
        },
      },
    ],
  },
  extensionsToTreatAsEsm: ['.ts'],
};
