export default {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/packages', '<rootDir>/apps', '<rootDir>/tests'],
  testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  moduleNameMapper: {
    '@omega-v/types': '<rootDir>/packages/types/src/index.ts',
    '@omega-v/observer': '<rootDir>/packages/observer/src/index.ts',
    '@omega-v/verification': '<rootDir>/packages/verification/src/index.ts',
    '@omega-v/attestation': '<rootDir>/packages/attestation/src/index.ts',
    '@omega-v/store': '<rootDir>/packages/store/src/index.ts',
    '@omega-v/ir': '<rootDir>/packages/ir/src/index.ts',
    '@omega-v/compiler': '<rootDir>/packages/compiler/src/index.ts',
    '@omega-v/sdk': '<rootDir>/packages/sdk/src/index.ts',
    '@omega-v/cli': '<rootDir>/packages/cli/src/index.ts',
    '@omega-v/agents': '<rootDir>/packages/agents/src/index.ts',
    '@omega-v/mood': '<rootDir>/packages/mood/src/index.ts',
    '@omega-v/friction': '<rootDir>/packages/friction/src/index.ts',
    '@omega-v/graph': '<rootDir>/packages/graph/src/index.ts',
    '@omega-v/security': '<rootDir>/packages/security/src/index.ts',
    '@omega-v/evolution': '<rootDir>/packages/evolution/src/index.ts',
    '@omega-v/learning': '<rootDir>/packages/learning/src/index.ts',
    '@omega-v/governance': '<rootDir>/packages/governance/src/index.ts',
    '@omega-v/evidence': '<rootDir>/packages/evidence/src/index.ts',
    '@omega-v/green': '<rootDir>/packages/green/src/index.ts',
    '@omega-v/human': '<rootDir>/packages/human/src/index.ts',
    '@omega-v/edge': '<rootDir>/packages/edge/src/index.ts',
    '@omega-v/analytics': '<rootDir>/packages/analytics/src/index.ts',
    '@omega-v/scheduler': '<rootDir>/packages/scheduler/src/index.ts',
    '@omega-v/telemetry': '<rootDir>/packages/telemetry/src/index.ts',
    '@omega-v/vaas': '<rootDir>/packages/vaas/src/index.ts',
    '@omega-v/replay': '<rootDir>/packages/replay/src/index.ts',
    '@omega-v/contract': '<rootDir>/packages/contract/src/index.ts',
    '@omega-v/auth': '<rootDir>/packages/auth/src/index.ts',
    '@omega-v/federation': '<rootDir>/packages/federation/src/index.ts',
  },
  collectCoverageFrom: [
    'packages/*/src/**/*.ts',
    '!packages/cli/src/bin.ts',
    '!**/*.d.ts',
    '!**/node_modules/**',
    '!**/dist/**',
  ],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
};
