export const WATER_FLOW_STAGES = [
  'REALITY',
  'ATTENTION',
  'INTENTION',
  'ACTION',
  'CONSEQUENCE',
  'OBSERVATION',
  'LEARNING',
  'RETURN',
] as const;

export type WaterFlowStage = (typeof WATER_FLOW_STAGES)[number];
export type WaterFlowStatus = 'VERIFIED' | 'DIVERGENT' | 'UNKNOWN' | 'NOT_EXECUTED';

export const LIVING_WATER_STAGES = [
  'SOURCE',
  'DROP',
  'FLOW',
  'CONTACT',
  'OBSERVE',
  'REFLECT',
  'VERIFY',
  'CHANGE',
  'RECONCILE',
  'REMEMBER',
  'RETURN',
  'NEW_DROP',
] as const;

export type LivingWaterStage = (typeof LIVING_WATER_STAGES)[number];
export type LivingWaterStageStatus = 'MODEL_ONLY' | 'UNKNOWN' | 'DIVERGENT' | 'NOT_EXECUTED';

export interface WaterFlowFrameView {
  flowVersion: 'omega.water-flow.v1';
  stage: WaterFlowStage;
  sequence: number;
  state: string;
  transition: string;
  traceId: string;
  deterministic: true;
  bounds: { maxSteps: number };
  provenance: {
    source: 'local-water-flow';
    verified: false;
    note: string;
  };
}

export interface WaterFlowCommandEnvelope {
  readonly waterFlow?: readonly WaterFlowFrameView[] | null;
}

export interface LivingWaterStepView {
  readonly stage: LivingWaterStage;
  readonly status: LivingWaterStageStatus;
  readonly machineStages: readonly WaterFlowStage[];
  readonly meaning: string;
}

export interface WaterFlowSummary {
  status: WaterFlowStatus;
  stages: readonly WaterFlowStage[];
  traceId: string | null;
  maxSteps: number;
  note: string;
  livingWaterSteps: readonly LivingWaterStepView[];
}

const KNOWN_STAGES = new Set<string>(WATER_FLOW_STAGES);

const LIVING_WATER_BINDINGS: readonly {
  stage: LivingWaterStage;
  machineStages: readonly WaterFlowStage[];
  meaning: string;
}[] = [
  { stage: 'SOURCE', machineStages: ['REALITY'], meaning: 'The v1 REALITY label carries local state context; it does not independently verify the source.' },
  { stage: 'DROP', machineStages: ['INTENTION'], meaning: 'One intent, event, person, or object; v1 represents the intent text.' },
  { stage: 'FLOW', machineStages: ['ACTION'], meaning: 'A bounded process model; v1 frames do not prove execution.' },
  { stage: 'CONTACT', machineStages: ['CONSEQUENCE'], meaning: 'A possible ripple or contact; v1 does not establish an external impact.' },
  { stage: 'OBSERVE', machineStages: ['OBSERVATION'], meaning: 'An observation-shaped model stage; it is not an external observation receipt.' },
  { stage: 'REFLECT', machineStages: ['LEARNING'], meaning: 'A reflection/learning label in the model, not a recorded human conclusion.' },
  { stage: 'VERIFY', machineStages: [], meaning: 'Not a distinct v1 water-flow stage; verification needs separate evidence.' },
  { stage: 'CHANGE', machineStages: ['ACTION'], meaning: 'The v1 action label does not grant authority or prove a change occurred.' },
  { stage: 'RECONCILE', machineStages: [], meaning: 'Not a distinct v1 water-flow stage; compare expected and observed states separately.' },
  { stage: 'REMEMBER', machineStages: [], meaning: 'A trace ID labels this trace; v1 does not claim durable memory.' },
  { stage: 'RETURN', machineStages: ['RETURN'], meaning: 'A modeled return step; it does not imply a new intent was submitted.' },
  { stage: 'NEW_DROP', machineStages: [], meaning: 'A later intent is a separate event and is not generated by this trace.' },
];

export function waterFlowFramesFromCommand(
  command: WaterFlowCommandEnvelope | null | undefined,
): readonly WaterFlowFrameView[] | null {
  const frames = command?.waterFlow;
  return Array.isArray(frames) ? frames : null;
}

function isWaterFlowFrame(value: unknown): value is WaterFlowFrameView {
  if (!value || typeof value !== 'object') return false;
  const frame = value as Partial<WaterFlowFrameView>;
  if (typeof frame.bounds !== 'object' || frame.bounds === null) return false;
  if (typeof frame.provenance !== 'object' || frame.provenance === null) return false;
  return (
    frame.flowVersion === 'omega.water-flow.v1' &&
    typeof frame.stage === 'string' &&
    KNOWN_STAGES.has(frame.stage) &&
    typeof frame.sequence === 'number' &&
    Number.isInteger(frame.sequence) &&
    typeof frame.state === 'string' &&
    typeof frame.transition === 'string' &&
    typeof frame.traceId === 'string' &&
    frame.deterministic === true &&
    Number.isInteger(frame.bounds.maxSteps) &&
    frame.bounds.maxSteps >= 1 &&
    frame.bounds.maxSteps <= WATER_FLOW_STAGES.length &&
    frame.sequence >= 0 &&
    frame.sequence < frame.bounds.maxSteps &&
    typeof frame.provenance.source === 'string' &&
    typeof frame.provenance.verified === 'boolean' &&
    typeof frame.provenance.note === 'string'
  );
}

function livingWaterSteps(
  stages: readonly WaterFlowStage[],
  hasFrames: boolean,
  traceStatus: WaterFlowStatus,
): readonly LivingWaterStepView[] {
  return LIVING_WATER_BINDINGS.map((binding) => {
    let status: LivingWaterStageStatus;
    if (!hasFrames) status = 'NOT_EXECUTED';
    else if (traceStatus === 'DIVERGENT') status = 'DIVERGENT';
    else if (binding.machineStages.some((stage) => stages.includes(stage))) status = 'MODEL_ONLY';
    else status = 'UNKNOWN';

    return { ...binding, status };
  });
}

export function summarizeWaterFlow(frames: readonly WaterFlowFrameView[] | null | undefined): WaterFlowSummary {
  if (!frames || frames.length === 0) {
    return {
      status: 'NOT_EXECUTED',
      stages: [],
      traceId: null,
      maxSteps: 0,
      note: 'No active command receipt supplied; no Living Water step is claimed as executed.',
      livingWaterSteps: livingWaterSteps([], false, 'NOT_EXECUTED'),
    };
  }

  const validFrames = frames.filter(isWaterFlowFrame);
  const first = validFrames[0];
  const stages = validFrames.map((frame) => frame.stage);
  const contractMatches =
    validFrames.length === frames.length &&
    validFrames.length > 0 &&
    validFrames.every((frame) => frame.provenance.source === 'local-water-flow' && frame.provenance.verified === false);
  const status: WaterFlowStatus = contractMatches ? 'UNKNOWN' : 'DIVERGENT';

  return {
    status,
    stages,
    traceId: first?.traceId ?? null,
    maxSteps: first?.bounds.maxSteps ?? 0,
    note: contractMatches
      ? 'The v1 frames are deterministic local representations. A mapped stage is MODEL_ONLY, not proof of execution, observation, or verification; unmapped steps remain UNKNOWN.'
      : 'Frame shape or provenance diverges from the bounded local-water-flow contract; reconcile before relying on this trace.',
    livingWaterSteps: livingWaterSteps(stages, true, status),
  };
}
