import assert from 'node:assert/strict';
import { describe, it, afterEach } from 'node:test';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../../apps/api/dist/index.js';

describe('market intelligence evidence route', () => {
  const originalFetch = globalThis.fetch;
  afterEach(() => { globalThis.fetch = originalFetch; });

  it('normalizes provider observations and reports evidence metadata', async () => {
    process.env.OMEGA_AUTH_MODE = 'local';
    process.env.OMEGA_PERSISTENCE = 'off';
    process.env.FINNHUB_API_KEY = 'test-key';
    globalThis.fetch = (async (input: string | URL | Request) => {
      const url = String(input);
      if (url.includes('finnhub')) return new Response(JSON.stringify({ c: 100, d: 2, dp: 2 }), { status: 200 });
      const id = url.includes('bitcoin') ? 'bitcoin' : 'ethereum';
      return new Response(JSON.stringify({ [id]: { usd: id === 'bitcoin' ? 60000 : 3000, usd_24h_change: id === 'bitcoin' ? 1.5 : -1 } }), { status: 200 });
    }) as typeof fetch;
    const directory = mkdtempSync(join(tmpdir(), 'omega-market-'));
    const databasePath = join(directory, 'market.db');
    const app = createApp(databasePath, false);
    const response = await app.inject({ method: 'GET', url: '/v1/market/snapshot' });
    assert.equal(response.statusCode, 200);
    const body = response.json();
    assert.equal(body.success, true);
    assert.equal(body.assets.length, 6);
    assert.equal(body.evidence.live, true);
    assert.equal(body.evidence.providerCount, 2);
    assert.match(body.signal, /leads relative momentum/);
    const addWatch = await app.inject({ method: 'POST', url: '/v1/market/watchlist', payload: { symbol: 'ETH', thresholdPercent: 0.5 } });
    assert.equal(addWatch.statusCode, 201);
    const alerts = await app.inject({ method: 'GET', url: '/v1/market/alerts' });
    assert.equal(alerts.statusCode, 200);
    assert.equal(alerts.json().alerts.some((alert: { symbol: string }) => alert.symbol === 'ETH'), true);
    const beforeScanHistory = await app.inject({ method: 'GET', url: '/v1/market/alerts/history' });
    assert.equal(beforeScanHistory.json().events.length, 0);
    const beforeRuns = await app.inject({ method: 'GET', url: '/v1/market/scans/history' });
    assert.equal(beforeRuns.json().runs.length, 0);
    const scan = await app.inject({ method: 'POST', url: '/v1/market/scan' });
    assert.equal(scan.statusCode, 200);
    const firstScan = scan.json();
    assert.equal(firstScan.recordedAlerts.some((alert: { symbol: string }) => alert.symbol === 'ETH'), true);
    const firstHistory = await app.inject({ method: 'GET', url: '/v1/market/alerts/history' });
    assert.equal(firstHistory.json().events.length, firstScan.recordedAlerts.length);
    const firstRuns = await app.inject({ method: 'GET', url: '/v1/market/scans/history' });
    assert.equal(firstRuns.json().runs.length, 1);
    assert.equal(firstRuns.json().runs[0].recordedCount, firstScan.recordedAlerts.length);
    const repeatedScan = await app.inject({ method: 'POST', url: '/v1/market/scan' });
    assert.equal(repeatedScan.statusCode, 200);
    assert.equal(repeatedScan.json().suppressedCount > 0, true);
    const history = await app.inject({ method: 'GET', url: '/v1/market/alerts/history' });
    assert.equal(history.statusCode, 200);
    assert.equal(history.json().events.length, firstHistory.json().events.length);
    const runs = await app.inject({ method: 'GET', url: '/v1/market/scans/history' });
    assert.equal(runs.json().runs.length, 2);
    const originalRequireLive = process.env.OMEGA_MARKET_SCAN_REQUIRE_LIVE;
    process.env.OMEGA_MARKET_SCAN_REQUIRE_LIVE = '1';
    globalThis.fetch = (async () => { throw new Error('provider_unavailable'); }) as typeof fetch;
    const failedScan = await app.inject({ method: 'POST', url: '/v1/market/scan' });
    assert.equal(failedScan.statusCode, 503);
    assert.equal(failedScan.json().error, 'MARKET_SCAN_FAILED');
    assert.equal(failedScan.json().scanRun.status, 'failed');
    const allRuns = await app.inject({ method: 'GET', url: '/v1/market/scans/history' });
    assert.equal(allRuns.json().runs.length, 3);
    if (originalRequireLive === undefined) delete process.env.OMEGA_MARKET_SCAN_REQUIRE_LIVE;
    else process.env.OMEGA_MARKET_SCAN_REQUIRE_LIVE = originalRequireLive;
    globalThis.fetch = originalFetch;
    const removeWatch = await app.inject({ method: 'DELETE', url: '/v1/market/watchlist/ETH' });
    assert.equal(removeWatch.statusCode, 200);
    await app.close();
    const restarted = createApp(databasePath, false);
    const persisted = await restarted.inject({ method: 'GET', url: '/v1/market/watchlist' });
    assert.equal(persisted.json().items.some((item: { symbol: string }) => item.symbol === 'NVDA'), true);
    assert.equal(persisted.json().items.some((item: { symbol: string }) => item.symbol === 'ETH'), false);
    const persistedRuns = await restarted.inject({ method: 'GET', url: '/v1/market/scans/history' });
    assert.equal(persistedRuns.json().runs.length, 3);
    await restarted.close();
    rmSync(directory, { recursive: true, force: true });
  });
});
