export type NetworkNodeKind = 'source' | 'human' | 'organ' | 'worker' | 'observer' | 'runtime' | 'memory' | 'external';
export type NetworkEdgeKind = 'connects' | 'informs' | 'observes' | 'depends-on' | 'reconciles' | 'derives';
export type NetworkSignalKind = 'proposal' | 'evidence' | 'warning' | 'dissent' | 'observation';
export type NetworkKnowledgeState = 'PROPOSED' | 'OBSERVED' | 'VERIFIED' | 'DIVERGENT' | 'UNKNOWN';
export interface NetworkProvenance { readonly source: string; readonly observedAt: string; readonly attributedTo: string | null; readonly evidenceRefs: readonly string[]; }
export interface NetworkNode { readonly id: string; readonly kind: NetworkNodeKind; readonly label: string; readonly state: NetworkKnowledgeState; readonly provenance: NetworkProvenance; }
export interface NetworkEdge { readonly id: string; readonly from: string; readonly to: string; readonly kind: NetworkEdgeKind; readonly bounded: true; readonly authority: string | null; readonly policy: string | null; }
export interface NetworkSignal { readonly id: string; readonly kind: NetworkSignalKind; readonly sourceNodeId: string; readonly targetNodeIds: readonly string[]; readonly payloadDigest: string; readonly state: NetworkKnowledgeState; readonly provenance: NetworkProvenance; }
export interface NetworkGraph { readonly version: 'network-intelligence.v1'; readonly nodes: readonly NetworkNode[]; readonly edges: readonly NetworkEdge[]; readonly signals: readonly NetworkSignal[]; }
export interface NetworkValidationResult { readonly valid: boolean; readonly errors: readonly string[]; }
export function validateNetworkGraph(graph: NetworkGraph): NetworkValidationResult { const errors: string[] = []; const nodeIds = new Set(graph.nodes.map((node) => node.id)); if (graph.version !== 'network-intelligence.v1') errors.push('unsupported network-intelligence version'); for (const edge of graph.edges) { if (!nodeIds.has(edge.from)) errors.push('edge '+edge.id+' references unknown source node '+edge.from); if (!nodeIds.has(edge.to)) errors.push('edge '+edge.id+' references unknown target node '+edge.to); if (edge.bounded !== true) errors.push('edge '+edge.id+' must be explicitly bounded'); } for (const signal of graph.signals) { if (!nodeIds.has(signal.sourceNodeId)) errors.push('signal '+signal.id+' references unknown source node '+signal.sourceNodeId); for (const targetId of signal.targetNodeIds) if (!nodeIds.has(targetId)) errors.push('signal '+signal.id+' references unknown target node '+targetId); } return { valid: errors.length === 0, errors }; }
