import { createHash, randomUUID } from 'node:crypto';

export type OmegaGeneration = 'LIVING' | 'MATTER';
export type OmegaForm = 'HUMAN' | 'ANIMAL' | 'PLANT' | 'WATER';
export type OmegaMotion = 0 | 1;
export type OmegaScale = 'NEEDLE' | 'PLANET';
export type OmegaDecision = 'ALLOW' | 'DENY' | 'REVIEW';
export type OmegaRoute = 0 | 1;
export type OmegaExecution = 'EXECUTED' | 'NOT_EXECUTED' | 'UNCONFIRMED';
export type OmegaVerification = 'VERIFIED' | 'DIVERGENT' | 'UNKNOWN' | 'NOT_EXECUTED';

export interface OmegaCoreState {
  readonly g: OmegaGeneration;
  readonly f: OmegaForm;
  readonly m: OmegaMotion;
  readonly s: OmegaScale;
}

export interface OmegaExecutionReceipt {
  /** Stable identifier supplied by the executor that actually ran the operation. */
  readonly id: string;
  readonly source: string;
  /** ISO-8601 timestamp supplied by the executor; not generated by this evaluator. */
  readonly recordedAt: string;
  readonly transactionId?: string;
}

export interface OmegaObservation {
  /** Stable identifier for an observation that actually exists. */
  readonly id: string;
  readonly source: string;
  /** ISO-8601 timestamp supplied by the observing system. */
  readonly recordedAt: string;
  /** Evidence reference for the observed result. */
  readonly evidenceId: string;
  /** Receipt ID this observation directly reconciles. */
  readonly executionReceiptId: string;
  /** Undefined means that observation exists but no comparison has been established. */
  readonly expectedMatchesActual?: boolean;
}

/**
 * Trusted adapters must validate provenance/authenticity, not just field shape.
 * Missing, false, or throwing verifiers fail closed.
 */
export interface OmegaEvidenceTrust {
  verifyExecutionReceipt(receipt: OmegaExecutionReceipt): boolean;
  verifyObservation(observation: OmegaObservation): boolean;
}

export interface OmegaCycleInput extends OmegaCoreState {
  readonly evidence: boolean;
  readonly evidenceId: string;
  readonly authority: boolean;
  readonly authorityId: string;
  readonly policyId: string;
  readonly bounded: boolean;
  /** Receipt from an external executor. This class does not execute external actions. */
  readonly executionReceipt?: OmegaExecutionReceipt;
  /** Evidence from an external observer, not a synthetic marker. */
  readonly observation?: OmegaObservation;
}

export interface OmegaCycleResult {
  readonly decision: OmegaDecision;
  readonly route: OmegaRoute;
  readonly execution: OmegaExecution;
  readonly verification: OmegaVerification;
  readonly eventId: string;
  readonly tx?: string;
  readonly observationId?: string;
  readonly reason?: string;
}

interface LedgerEntry {
  readonly eventId: string;
  readonly tx?: string;
  readonly decision: OmegaDecision;
  readonly route: OmegaRoute;
  readonly execution: OmegaExecution;
  readonly verification: OmegaVerification;
  readonly state: OmegaCoreState;
  readonly evidenceId?: string;
  readonly authorityId?: string;
  readonly policyId?: string;
  readonly executionReceipt?: OmegaExecutionReceipt;
  readonly observation?: OmegaObservation;
  readonly reason?: string;
  readonly previousHash: string;
  readonly hash: string;
}

const GEN: readonly OmegaGeneration[] = ['LIVING', 'MATTER'];
const FORM: readonly OmegaForm[] = ['HUMAN', 'ANIMAL', 'PLANT', 'WATER'];
const MOTION: readonly OmegaMotion[] = [0, 1];
const SCALE: readonly OmegaScale[] = ['NEEDLE', 'PLANET'];

export class OceanicosRealityMatrix {
  private readonly entries: LedgerEntry[] = [];

  public constructor(private readonly evidenceTrust?: OmegaEvidenceTrust) {}

  /**
   * Evaluates admission and reconciles caller-supplied execution/observation evidence.
   * It deliberately does not execute external actions or invent receipts.
   */
  public cycle(input: OmegaCycleInput): OmegaCycleResult {
    const eventId = 'event_' + randomUUID();
    const invalid = this.validate(input);

    if (invalid) {
      this.appendAndSeal({
        eventId,
        decision: 'DENY',
        route: 0,
        execution: 'NOT_EXECUTED',
        verification: 'NOT_EXECUTED',
        state: this.stateOf(input),
        evidenceId: input.evidenceId,
        authorityId: input.authorityId,
        policyId: input.policyId,
        reason: invalid,
        previousHash: this.tipHash(),
        hash: '',
      });
      return {
        decision: 'DENY',
        route: 0,
        execution: 'NOT_EXECUTED',
        verification: 'NOT_EXECUTED',
        eventId,
        reason: invalid,
      };
    }

    const receiptWasProvided = input.executionReceipt !== undefined;
    const receiptIsWellFormed = this.validExecutionReceipt(input.executionReceipt);
    const receiptIsTrusted = receiptIsWellFormed && this.isTrustedExecutionReceipt(input.executionReceipt);
    const executionReceipt = receiptIsTrusted ? input.executionReceipt : undefined;

    const observationWasProvided = input.observation !== undefined;
    const observationIsWellFormed = this.validObservation(input.observation);
    const observationBindsToReceipt = Boolean(
      executionReceipt &&
      observationIsWellFormed &&
      input.observation.executionReceiptId === executionReceipt.id
    );
    const observationIsTrusted = observationBindsToReceipt && this.isTrustedObservation(input.observation);
    const observation = observationIsTrusted ? input.observation : undefined;

    // Admission is not execution. Only a receipt accepted by the trusted adapter can confirm execution.
    const execution: OmegaExecution = executionReceipt ? 'EXECUTED' : 'UNCONFIRMED';
    const verification: OmegaVerification = !executionReceipt
      ? 'UNKNOWN'
      : !observation || observation.expectedMatchesActual === undefined
        ? 'UNKNOWN'
        : observation.expectedMatchesActual
          ? 'VERIFIED'
          : 'DIVERGENT';

    let reason: string | undefined;
    if (!executionReceipt) {
      reason = !receiptWasProvided
        ? 'NO_EXECUTION_RECEIPT'
        : !receiptIsWellFormed
          ? 'INVALID_EXECUTION_RECEIPT'
          : 'UNTRUSTED_EXECUTION_RECEIPT';
    } else if (!observation) {
      reason = !observationWasProvided
        ? 'NO_OBSERVATION'
        : !observationIsWellFormed
          ? 'INVALID_OBSERVATION'
          : !observationBindsToReceipt
            ? 'OBSERVATION_RECEIPT_MISMATCH'
            : 'UNTRUSTED_OBSERVATION';
    } else if (observation.expectedMatchesActual === undefined) {
      reason = 'OBSERVATION_HAS_NO_COMPARISON';
    }

    const tx = executionReceipt?.transactionId ?? executionReceipt?.id;
    this.appendAndSeal({
      eventId,
      tx,
      decision: 'ALLOW',
      route: 1,
      execution,
      verification,
      state: this.stateOf(input),
      evidenceId: input.evidenceId,
      authorityId: input.authorityId,
      policyId: input.policyId,
      executionReceipt,
      observation,
      reason,
      previousHash: this.tipHash(),
      hash: '',
    });

    return {
      decision: 'ALLOW',
      route: 1,
      execution,
      verification,
      eventId,
      tx,
      observationId: observation?.id,
      reason,
    };
  }

  public ledger(): readonly LedgerEntry[] {
    // Return detached snapshots so callers cannot mutate nested ledger records in place.
    return this.entries.map((entry) => ({
      ...entry,
      state: { ...entry.state },
      ...(entry.executionReceipt ? { executionReceipt: { ...entry.executionReceipt } } : {}),
      ...(entry.observation ? { observation: { ...entry.observation } } : {}),
    }));
  }

  public verifyLedger(): boolean {
    let previousHash = 'GENESIS';
    for (const entry of this.entries) {
      const { hash, ...unsigned } = entry;
      if (entry.previousHash !== previousHash) return false;
      if (hash !== digest(unsigned)) return false;
      previousHash = hash;
    }
    return true;
  }

  private validate(input: OmegaCycleInput): string | null {
    if (!GEN.includes(input.g)) return 'INVALID_GENERATION';
    if (!FORM.includes(input.f)) return 'INVALID_FORM';
    if (!MOTION.includes(input.m)) return 'INVALID_MOTION';
    if (!SCALE.includes(input.s)) return 'INVALID_SCALE';
    if (!input.evidence) return 'MISSING_EVIDENCE';
    if (!isNonEmpty(input.evidenceId)) return 'MISSING_EVIDENCE_REFERENCE';
    if (!input.authority) return 'MISSING_AUTHORITY';
    if (!isNonEmpty(input.authorityId)) return 'MISSING_AUTHORITY_REFERENCE';
    if (!isNonEmpty(input.policyId)) return 'MISSING_POLICY_REFERENCE';
    if (!input.bounded) return 'UNBOUNDED_TRANSITION';
    return null;
  }

  private validExecutionReceipt(
    receipt: OmegaExecutionReceipt | undefined,
  ): receipt is OmegaExecutionReceipt {
    return Boolean(
      receipt &&
      isNonEmpty(receipt.id) &&
      isNonEmpty(receipt.source) &&
      isTimestamp(receipt.recordedAt) &&
      (receipt.transactionId === undefined || isNonEmpty(receipt.transactionId)),
    );
  }

  private validObservation(observation: OmegaObservation | undefined): observation is OmegaObservation {
    return Boolean(
      observation &&
      isNonEmpty(observation.id) &&
      isNonEmpty(observation.source) &&
      isTimestamp(observation.recordedAt) &&
      isNonEmpty(observation.evidenceId) &&
      isNonEmpty(observation.executionReceiptId) &&
      (observation.expectedMatchesActual === undefined ||
        typeof observation.expectedMatchesActual === 'boolean'),
    );
  }

  private isTrustedExecutionReceipt(receipt: OmegaExecutionReceipt): boolean {
    try {
      return this.evidenceTrust?.verifyExecutionReceipt(receipt) === true;
    } catch {
      return false;
    }
  }

  private isTrustedObservation(observation: OmegaObservation): boolean {
    try {
      return this.evidenceTrust?.verifyObservation(observation) === true;
    } catch {
      return false;
    }
  }

  private stateOf(input: OmegaCoreState): OmegaCoreState {
    return { g: input.g, f: input.f, m: input.m, s: input.s };
  }

  private tipHash(): string {
    return this.entries.length ? this.entries[this.entries.length - 1].hash : 'GENESIS';
  }

  private appendAndSeal(entry: LedgerEntry): void {
    this.entries.push(entry);
    const last = this.entries[this.entries.length - 1];
    const { hash, ...unsigned } = last;
    this.entries[this.entries.length - 1] = { ...unsigned, hash: digest(unsigned) };
  }
}

function isNonEmpty(value: unknown): value is string {
  return typeof value === 'string' && value.trim().length > 0;
}

function isTimestamp(value: unknown): value is string {
  return isNonEmpty(value) && Number.isFinite(Date.parse(value));
}

function digest(value: Omit<LedgerEntry, 'hash'>): string {
  return createHash('sha256').update(JSON.stringify(value)).digest('hex');
}
